import express from 'express'; import helmet from 'helmet'; import cors from 'cors'; import cookieParser from 'cookie-parser'; import rateLimit from 'express-rate-limit'; import argon2 from 'argon2';
import {pool,transaction,audit} from './db.js'; import {config} from './config.js'; import {issueSession,clearSession,requireAuth} from './auth.js'; import {registerSchema,businessSchema,productSchema,saleSchema,customerSchema,expenseSchema,customerPaymentSchema,feedbackSchema,aiQuestionSchema,parse} from './validation.js';
import {saleAmounts} from './finance.js';
const app=express(); app.disable('x-powered-by'); app.use(helmet({crossOriginResourcePolicy:{policy:'same-site'}})); app.use(cors({origin:config.corsOrigin,credentials:true})); app.use(express.json({limit:'100kb'})); app.use(cookieParser());
app.use((req,res,next)=>{if(!['POST','PUT','PATCH','DELETE'].includes(req.method))return next();const origin=req.get('origin');if(origin!==config.appUrl)return res.status(403).json({error:{code:'CSRF_REJECTED',message:'Request origin is not allowed.'}});next();});
app.use('/api/v1/auth',rateLimit({windowMs:15*60*1000,limit:20,standardHeaders:'draft-8',legacyHeaders:false}));
const asyncRoute=fn=>(req,res,next)=>Promise.resolve(fn(req,res,next)).catch(next);
async function businessContext(req,res,next){const businessId=req.header('x-business-id');if(!businessId)return res.status(400).json({error:{code:'BUSINESS_REQUIRED',message:'Select a business.'}});const member=await transaction({userId:req.user.id},c=>c.query('SELECT role FROM business_members WHERE business_id=$1 AND user_id=$2',[businessId,req.user.id]));if(!member.rowCount)return res.status(403).json({error:{code:'FORBIDDEN',message:'You do not have access to this business.'}});req.actor={userId:req.user.id,businessId,role:member.rows[0].role};next();}
function requireRole(...roles){return(req,res,next)=>roles.includes(req.actor.role)?next():res.status(403).json({error:{code:'FORBIDDEN',message:'Your role cannot perform this action.'}})}

app.get('/health',asyncRoute(async(_req,res)=>{await pool.query('SELECT 1');res.json({data:{status:'ok'}})}));
app.post('/api/v1/auth/register',asyncRoute(async(req,res)=>{const input=parse(registerSchema,req.body,res);if(!input)return;const hash=await argon2.hash(input.password,{type:argon2.argon2id,memoryCost:19456,timeCost:2,parallelism:1});try{const user=(await pool.query('INSERT INTO users(email,password_hash) VALUES(lower($1),$2) RETURNING id,email',[input.email,hash])).rows[0];await issueSession(res,user);res.status(201).json({data:{user:{id:user.id,email:user.email}}});}catch(e){if(e.code==='23505')return res.status(409).json({error:{code:'EMAIL_IN_USE',message:'An account already exists for this email.'}});throw e;}}));
app.post('/api/v1/auth/login',asyncRoute(async(req,res)=>{const input=parse(registerSchema,req.body,res);if(!input)return;const result=await pool.query('SELECT id,email,password_hash FROM users WHERE email=lower($1) AND deleted_at IS NULL',[input.email]);if(!result.rowCount||!await argon2.verify(result.rows[0].password_hash,input.password))return res.status(401).json({error:{code:'INVALID_CREDENTIALS',message:'Email or password is incorrect.'}});await issueSession(res,result.rows[0]);res.json({data:{user:{id:result.rows[0].id,email:result.rows[0].email}}});}));
app.post('/api/v1/auth/logout',requireAuth,asyncRoute(async(req,res)=>{clearSession(res);res.status(204).end();}));
app.get('/api/v1/me',requireAuth,asyncRoute(async(req,res)=>{const businesses=await transaction({userId:req.user.id},c=>c.query('SELECT b.id,b.name,b.country_code,b.currency_code,m.role FROM businesses b JOIN business_members m ON m.business_id=b.id WHERE m.user_id=$1 AND b.deleted_at IS NULL',[req.user.id]));res.json({data:{user:req.user,businesses:businesses.rows}})}));
app.post('/api/v1/auth/delete-account',requireAuth,asyncRoute(async(req,res)=>{await pool.query('UPDATE users SET deleted_at=now(),email=concat(id,\'@deleted.invalid\'),password_hash=\'deleted\' WHERE id=$1',[req.user.id]);clearSession(res);res.status(204).end();}));

app.post('/api/v1/businesses',requireAuth,asyncRoute(async(req,res)=>{const input=parse(businessSchema,req.body,res);if(!input)return;const created=await transaction({userId:req.user.id},async c=>{const b=(await c.query('INSERT INTO businesses(name,country_code,currency_code) VALUES($1,$2,$3) RETURNING id,name,country_code,currency_code',[input.name,input.countryCode,input.currencyCode])).rows[0];await c.query('INSERT INTO business_members(business_id,user_id,role) VALUES($1,$2,\'owner\')',[b.id,req.user.id]);await audit(c,{userId:req.user.id,businessId:b.id},'business.created','business',b.id);return b;});res.status(201).json({data:created});}));
app.use('/api/v1',requireAuth,asyncRoute(businessContext));
app.get('/api/v1/products',asyncRoute(async(req,res)=>{const rows=await transaction(req.actor,c=>c.query('SELECT id,name,sku,cost_price,selling_price,quantity,minimum_stock FROM products WHERE business_id=$1 ORDER BY name',[req.actor.businessId]));res.json({data:rows.rows});}));
app.post('/api/v1/products',requireRole('owner','manager'),asyncRoute(async(req,res)=>{const input=parse(productSchema,req.body,res);if(!input)return;const product=await transaction(req.actor,async c=>{const p=(await c.query('INSERT INTO products(business_id,name,sku,cost_price,selling_price,quantity,minimum_stock) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[req.actor.businessId,input.name,input.sku||null,input.costPrice,input.sellingPrice,input.quantity,input.minimumStock])).rows[0];if(p.quantity)await c.query("INSERT INTO inventory_movements(business_id,product_id,movement_type,quantity_delta) VALUES($1,$2,'opening',$3)",[req.actor.businessId,p.id,p.quantity]);await audit(c,req.actor,'product.created','product',p.id);return p;});res.status(201).json({data:product});}));
app.get('/api/v1/customers',asyncRoute(async(req,res)=>{const rows=await transaction(req.actor,c=>c.query("SELECT c.id,c.name,c.phone,c.email,COALESCE(sum(s.total) FILTER(WHERE s.payment_method='credit'),0)-COALESCE((SELECT sum(p.amount) FROM payments p WHERE p.customer_id=c.id),0) AS outstanding_balance FROM customers c LEFT JOIN sales s ON s.customer_id=c.id WHERE c.business_id=$1 GROUP BY c.id ORDER BY c.name",[req.actor.businessId]));res.json({data:rows.rows});}));
app.post('/api/v1/customers',requireRole('owner','manager','employee'),asyncRoute(async(req,res)=>{const input=parse(customerSchema,req.body,res);if(!input)return;const row=await transaction(req.actor,async c=>{const r=(await c.query('INSERT INTO customers(business_id,name,phone,email) VALUES($1,$2,$3,$4) RETURNING *',[req.actor.businessId,input.name,input.phone||null,input.email||null])).rows[0];await audit(c,req.actor,'customer.created','customer',r.id);return r;});res.status(201).json({data:row});}));
app.post('/api/v1/customers/:customerId/payments',requireRole('owner','manager'),asyncRoute(async(req,res)=>{const input=parse(customerPaymentSchema,req.body,res);if(!input)return;const payment=await transaction(req.actor,async c=>{const balance=(await c.query("SELECT COALESCE((SELECT sum(total) FROM sales WHERE business_id=$1 AND customer_id=$2 AND payment_method='credit'),0)-COALESCE((SELECT sum(amount) FROM payments WHERE business_id=$1 AND customer_id=$2),0) amount",[req.actor.businessId,req.params.customerId])).rows[0];if(Number(input.amount)>Number(balance.amount)){const e=new Error('Payment cannot exceed recorded credit balance');e.status=422;throw e;}const p=(await c.query('INSERT INTO payments(business_id,customer_id,amount,paid_at,created_by) SELECT $1,id,$3,COALESCE($4,now()),$5 FROM customers WHERE id=$2 AND business_id=$1 RETURNING *',[req.actor.businessId,req.params.customerId,input.amount,input.paidAt||null,req.actor.userId])).rows[0];if(!p){const e=new Error('Customer not found');e.status=404;throw e;}await audit(c,req.actor,'customer.payment_recorded','payment',p.id);return p;});res.status(201).json({data:payment});}));
app.get('/api/v1/expenses',asyncRoute(async(req,res)=>{const rows=await transaction(req.actor,c=>c.query('SELECT id,category,amount,payment_method,description,spent_at FROM expenses WHERE business_id=$1 ORDER BY spent_at DESC LIMIT 100',[req.actor.businessId]));res.json({data:rows.rows});}));
app.post('/api/v1/expenses',requireRole('owner','manager'),asyncRoute(async(req,res)=>{const input=parse(expenseSchema,req.body,res);if(!input)return;const expense=await transaction(req.actor,async c=>{const e=(await c.query('INSERT INTO expenses(business_id,category,amount,payment_method,description,spent_at,created_by) VALUES($1,$2,$3,$4,$5,COALESCE($6,now()),$7) RETURNING *',[req.actor.businessId,input.category,input.amount,input.paymentMethod,input.description||null,input.spentAt||null,req.actor.userId])).rows[0];await audit(c,req.actor,'expense.created','expense',e.id);return e;});res.status(201).json({data:expense});}));
app.post('/api/v1/sales',requireRole('owner','manager','employee'),asyncRoute(async(req,res)=>{const input=parse(saleSchema,req.body,res);if(!input)return;const sale=await transaction(req.actor,async c=>{const prior=await c.query('SELECT id,subtotal,discount,total,cost_total,sold_at FROM sales WHERE business_id=$1 AND idempotency_key=$2',[req.actor.businessId,input.idempotencyKey]);if(prior.rowCount)return {...prior.rows[0],replayed:true};const product=(await c.query('SELECT id,name,cost_price,quantity FROM products WHERE id=$1 AND business_id=$2 FOR UPDATE',[input.productId,req.actor.businessId])).rows[0];if(!product){const e=new Error('Product not found');e.status=404;throw e;}if(product.quantity<input.quantity){const e=new Error('Insufficient stock');e.status=409;throw e;}if(input.customerId){const customer=await c.query('SELECT 1 FROM customers WHERE id=$1 AND business_id=$2',[input.customerId,req.actor.businessId]);if(!customer.rowCount){const e=new Error('Customer not found');e.status=404;throw e;}}let amounts;try{amounts=saleAmounts(input.quantity,input.unitPrice,input.discount,product.cost_price)}catch(e){e.status=422;throw e;}const s=(await c.query('INSERT INTO sales(business_id,idempotency_key,customer_id,payment_method,subtotal,discount,total,cost_total,sold_at,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,COALESCE($9,now()),$10) RETURNING *',[req.actor.businessId,input.idempotencyKey,input.customerId||null,input.paymentMethod,amounts.subtotal,input.discount,amounts.total,amounts.costTotal,input.soldAt||null,req.actor.userId])).rows[0];await c.query('INSERT INTO sale_items(sale_id,product_id,product_name,quantity,unit_price,unit_cost,line_total) VALUES($1,$2,$3,$4,$5,$6,$7)',[s.id,product.id,product.name,input.quantity,input.unitPrice,product.cost_price,amounts.total]);await c.query('UPDATE products SET quantity=quantity-$1 WHERE id=$2',[input.quantity,product.id]);await c.query("INSERT INTO inventory_movements(business_id,product_id,movement_type,quantity_delta,reference_id) VALUES($1,$2,'sale',$3,$4)",[req.actor.businessId,product.id,-input.quantity,s.id]);await audit(c,req.actor,'sale.created','sale',s.id,{idempotencyKey:input.idempotencyKey});return s;});res.status(sale.replayed?200:201).json({data:sale});}));
app.get('/api/v1/dashboard',asyncRoute(async(req,res)=>{const stats=await transaction(req.actor,async c=>{const q=await c.query("SELECT COALESCE(sum(total) FILTER (WHERE sold_at::date=current_date),0) sales_today,COALESCE(sum(cost_total) FILTER (WHERE sold_at::date=current_date),0) costs_today FROM sales WHERE business_id=$1",[req.actor.businessId]);const e=await c.query("SELECT COALESCE(sum(amount) FILTER (WHERE spent_at::date=current_date),0) expenses_today FROM expenses WHERE business_id=$1",[req.actor.businessId]);const low=await c.query('SELECT id,name,quantity,minimum_stock FROM products WHERE business_id=$1 AND quantity<=minimum_stock ORDER BY quantity',[req.actor.businessId]);return {...q.rows[0],expenses_today:e.rows[0].expenses_today,low_stock:low.rows};});res.json({data:stats});}));
app.post('/api/v1/feedback',asyncRoute(async(req,res)=>{const input=parse(feedbackSchema,req.body,res);if(!input)return;const row=await transaction(req.actor,async c=>{if(input.aiMessageId){const found=await c.query('SELECT 1 FROM ai_messages WHERE id=$1 AND business_id=$2',[input.aiMessageId,req.actor.businessId]);if(!found.rowCount){const e=new Error('AI message not found');e.status=404;throw e;}}const r=(await c.query('INSERT INTO feedback(business_id,user_id,ai_message_id,kind,feature,rating,nps,comment) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id,kind,feature,rating,nps,comment,created_at',[req.actor.businessId,req.actor.userId,input.aiMessageId||null,input.kind,input.feature||null,input.rating??null,input.nps??null,input.comment||null])).rows[0];await audit(c,req.actor,'feedback.submitted','feedback',r.id);return r;});res.status(201).json({data:row});}));
app.get('/api/v1/feedback/summary',requireRole('owner','manager'),asyncRoute(async(req,res)=>{const rows=await transaction(req.actor,c=>c.query("SELECT count(*) FILTER(WHERE rating IS NOT NULL) AS ratings,round(avg(rating),2) AS average_rating,count(*) FILTER(WHERE nps>=9) AS promoters,count(*) FILTER(WHERE nps<=6) AS detractors,count(*) FILTER(WHERE nps IS NOT NULL) AS nps_responses FROM feedback WHERE business_id=$1",[req.actor.businessId]));const r=rows.rows[0],n=Number(r.nps_responses);res.json({data:{...r,nps:n?Math.round(((Number(r.promoters)-Number(r.detractors))/n)*100):null}})}));
app.post('/api/v1/ai/answer',rateLimit({windowMs:60_000,limit:30,standardHeaders:'draft-8',legacyHeaders:false}),asyncRoute(async(req,res)=>{const input=parse(aiQuestionSchema,req.body,res);if(!input)return;const reply=await transaction(req.actor,async c=>{const q=input.question.toLowerCase();let answer;if(/sales|sell|revenue/.test(q)){const r=(await c.query('SELECT COALESCE(sum(total),0) amount FROM sales WHERE business_id=$1 AND sold_at>=date_trunc(\'week\',now())',[req.actor.businessId])).rows[0];answer=`Calculated from your recorded data: sales this week are ${r.amount}.`;}else if(/expense|spend/.test(q)){const r=(await c.query('SELECT COALESCE(sum(amount),0) amount FROM expenses WHERE business_id=$1 AND spent_at>=date_trunc(\'month\',now())',[req.actor.businessId])).rows[0];answer=`Calculated from your recorded data: expenses this month are ${r.amount}.`;}else if(/low|stock|reorder/.test(q)){const r=(await c.query('SELECT name,quantity FROM products WHERE business_id=$1 AND quantity<=minimum_stock ORDER BY quantity LIMIT 10',[req.actor.businessId])).rows;answer=r.length?`Calculated from your recorded data: low-stock products are ${r.map(x=>`${x.name} (${x.quantity})`).join(', ')}.`:'Calculated from your recorded data: no products are at or below their minimum stock level.';}else answer='I do not have enough recorded business data to answer that accurately. I can answer questions about recorded sales, expenses, or low stock.';const m=(await c.query('INSERT INTO ai_messages(business_id,user_id,question,answer) VALUES($1,$2,$3,$4) RETURNING id,answer,created_at',[req.actor.businessId,req.actor.userId,input.question,answer])).rows[0];await audit(c,req.actor,'ai.question_answered','ai_message',m.id);return m;});res.json({data:reply});}));
app.use((_req,res)=>res.status(404).json({error:{code:'NOT_FOUND',message:'Endpoint not found.'}})); app.use((err,_req,res,_next)=>{console.error(err);res.status(err.status||500).json({error:{code:err.status?'REQUEST_FAILED':'INTERNAL_ERROR',message:err.status?err.message:'An unexpected error occurred.'}})});
export default app;
