import {z} from 'zod';
export const registerSchema=z.object({email:z.string().email().max(254),password:z.string().min(12).max(128)});
export const businessSchema=z.object({name:z.string().trim().min(2).max(160),countryCode:z.string().length(2).toUpperCase(),currencyCode:z.string().length(3).toUpperCase()});
export const productSchema=z.object({name:z.string().trim().min(1).max(160),sku:z.string().trim().max(80).optional(),costPrice:z.coerce.number().nonnegative(),sellingPrice:z.coerce.number().nonnegative(),quantity:z.coerce.number().int().nonnegative(),minimumStock:z.coerce.number().int().nonnegative().default(0)});
export const saleSchema=z.object({idempotencyKey:z.string().uuid(),productId:z.string().uuid(),quantity:z.coerce.number().int().positive(),unitPrice:z.coerce.number().nonnegative(),discount:z.coerce.number().nonnegative().default(0),customerId:z.string().uuid().nullable().optional(),paymentMethod:z.enum(['cash','mobile_money','bank_transfer','card','credit']),soldAt:z.coerce.date().optional()});
export const customerSchema=z.object({name:z.string().trim().min(1).max(160),phone:z.string().trim().max(40).optional(),email:z.string().email().max(254).optional()});
export const expenseSchema=z.object({category:z.string().trim().min(1).max(80),amount:z.coerce.number().positive(),paymentMethod:z.enum(['cash','mobile_money','bank_transfer','card']),description:z.string().trim().max(500).optional(),spentAt:z.coerce.date().optional()});
export const customerPaymentSchema=z.object({amount:z.coerce.number().positive(),paidAt:z.coerce.date().optional()});
export const feedbackSchema=z.object({kind:z.enum(['rating','nps','comment','bug','feature_request','ai_response']),feature:z.string().trim().max(80).optional(),rating:z.coerce.number().int().min(1).max(5).optional(),nps:z.coerce.number().int().min(0).max(10).optional(),comment:z.string().trim().max(2000).optional(),aiMessageId:z.string().uuid().optional()}).refine(v=>v.rating!==undefined||v.nps!==undefined||v.comment!==undefined,{message:'Provide a rating, score, or comment.'});
export const aiQuestionSchema=z.object({question:z.string().trim().min(2).max(1000)});
export function parse(schema,input,res){const value=schema.safeParse(input);if(value.success)return value.data;res.status(422).json({error:{code:'VALIDATION_ERROR',message:'Some fields need attention.',fieldErrors:value.error.flatten().fieldErrors}});return null;}
