const KEY='bizai-africa-v1';
const empty={business:null,products:[],sales:[],expenses:[],customers:[],payments:[],queue:[],seen:[]};
let state=JSON.parse(localStorage.getItem(KEY)||'null')||structuredClone(empty); let view='home';
const $=s=>document.querySelector(s), money=n=>new Intl.NumberFormat('en',{style:'currency',currency:state.business?.currency||'KES',maximumFractionDigits:2}).format(Number(n||0));
const API_DEFAULT='http://localhost:3001';
async function api(path,options={}){const headers={...(options.body?{'Content-Type':'application/json'}:{}),...(state.apiBusinessId?{'X-Business-Id':state.apiBusinessId}:{}),...(options.headers||{})};const response=await fetch(`${state.apiBase||API_DEFAULT}/api/v1${path}`,{...options,headers,credentials:'include'});if(response.status===204)return null;const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error?.message||'The server could not complete that request.');return result.data;}
const id=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`; const today=()=>new Date().toISOString().slice(0,10);
function save(){localStorage.setItem(KEY,JSON.stringify(state)); $('#sync').textContent=navigator.onLine?'● Synced':'● Offline — saved on device';}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function total(a){return a.reduce((s,x)=>s+Number(x.amount||x.total||0),0)}
function customerBalance(c){const credit=state.sales.filter(s=>s.customerId===c.id&&s.payment==='Credit').reduce((x,s)=>x+s.total,0);const paid=state.payments.filter(p=>p.customerId===c.id).reduce((x,p)=>x+p.amount,0);return credit-paid}
function setBusiness(b){state.business=b;save(); $('#setup').hidden=true;$('#app').hidden=false;render();}
$('#businessForm').onsubmit=e=>{e.preventDefault();setBusiness({name:$('#bizName').value.trim(),type:$('#bizType').value,countryCode:$('#country').value,currency:$('#currency').value});};
$('#demo').onclick=()=>{state={business:{name:'Amina’s Market',type:'Retail',countryCode:'KE',currency:'KES',demo:true},products:[{id:id(),name:'Rice 2kg',sku:'RIC-2',cost:250,sell:360,qty:18,min:8},{id:id(),name:'Cooking oil 1L',sku:'OIL-1',cost:210,sell:280,qty:4,min:6}],customers:[{id:'c-demo',name:'Musa Otieno',phone:'0712 000 000'}],sales:[],expenses:[],payments:[],queue:[],seen:[]};save();setBusiness(state.business)};
if(state.business){$('#setup').hidden=true;$('#app').hidden=false;}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{view=b.dataset.view;document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x===b));render();});
function render(){if(!state.business)return; $('#view').innerHTML=pages[view](); bind[view]?.();}
function metrics(){const d=today();const sales=state.sales.filter(s=>s.date===d), expenses=state.expenses.filter(x=>x.date===d);const rev=total(sales),cost=sales.reduce((n,s)=>n+s.cost,0),exp=total(expenses);return {rev,cost,exp,profit:rev-cost-exp,cash:sales.filter(s=>s.payment!=='Credit').reduce((n,s)=>n+s.total,0),credit:sales.filter(s=>s.payment==='Credit').reduce((n,s)=>n+s.total,0),debt:state.customers.reduce((n,c)=>n+customerBalance(c),0),stock:state.products.reduce((n,p)=>n+p.qty*p.cost,0)}}
const pages={
home(){const m=metrics(),low=state.products.filter(p=>p.qty<=p.min),recent=[...state.sales.map(s=>({...s,type:'Sale'})),...state.expenses.map(s=>({...s,type:'Expense'}))].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5);return `<div class="page-head"><div><p class="eyebrow">${esc(state.business.name)} · ${esc(state.business.type)}</p><h1>Today at a glance</h1></div><button id="quickSale">+ Record sale</button></div><div class="grid"><div class="card metric"><small>Sales today</small><strong>${money(m.rev)}</strong></div><div class="card metric"><small>Expenses today</small><strong>${money(m.exp)}</strong></div><div class="card metric"><small>Estimated profit</small><strong class="${m.profit>=0?'positive':'negative'}">${money(m.profit)}</strong></div><div class="card metric"><small>Cash received</small><strong>${money(m.cash)}</strong></div><div class="card metric"><small>Credit sales</small><strong>${money(m.credit)}</strong></div><div class="card metric"><small>Customer debt</small><strong>${money(m.debt)}</strong></div><div class="card metric"><small>Inventory value</small><strong>${money(m.stock)}</strong></div><div class="card metric"><small>Products</small><strong>${state.products.length}</strong></div></div>${low.length?`<div class="notice"><b>Low stock:</b> ${low.map(p=>esc(p.name)).join(', ')} ${low.length===1?'is':'are'} at or below its minimum level.</div>`:''}<div class="grid"><div class="card wide"><h2>Recent activity</h2>${recent.length?`<ul class="list">${recent.map(x=>`<li><span>${esc(x.type)} · ${esc(x.description||x.productName||'Transaction')}<br><small>${x.date}</small></span><b class="${x.type==='Expense'?'negative':'positive'}">${x.type==='Expense'?'-':'+'}${money(x.amount||x.total)}</b></li>`).join('')}</ul>`:'<p>No activity recorded yet. Add a product, then record your first sale.</p>'}</div><div class="card wide"><h2>Business health</h2><p>Calculated values are based on your recorded transactions. The assistant can explain sales, expenses, debt, and low stock without inventing data.</p><button class="secondary" id="askAI">Ask the assistant</button></div></div>`},
sales(){return `<div class="page-head"><h1>Sales</h1><button id="addSale">+ Record sale</button></div><div class="card"><table><thead><tr><th>Date</th><th>Product</th><th>Customer</th><th>Method</th><th>Total</th><th></th></tr></thead><tbody>${state.sales.length?state.sales.map(s=>`<tr><td>${s.date}</td><td>${esc(s.productName)} × ${s.qty}</td><td>${esc(state.customers.find(c=>c.id===s.customerId)?.name||'Walk-in')}</td><td>${esc(s.payment)}</td><td>${money(s.total)}</td><td><button class="secondary receipt" data-id="${s.id}">Receipt</button></td></tr>`).join(''):'<tr><td colspan="6">No sales yet.</td></tr>'}</tbody></table></div>`},
inventory(){return `<div class="page-head"><h1>Inventory</h1><button id="addProduct">+ Add product</button></div><div class="card"><table><thead><tr><th>Product</th><th>SKU</th><th>In stock</th><th>Cost</th><th>Selling</th><th>Status</th></tr></thead><tbody>${state.products.length?state.products.map(p=>`<tr><td>${esc(p.name)}</td><td>${esc(p.sku||'—')}</td><td>${p.qty}</td><td>${money(p.cost)}</td><td>${money(p.sell)}</td><td class="${p.qty<=p.min?'negative':'positive'}">${p.qty<=p.min?'Low stock':'Healthy'}</td></tr>`).join(''):'<tr><td colspan="6">No products yet.</td></tr>'}</tbody></table></div>`},
customers(){return `<div class="page-head"><h1>Customers</h1><button id="addCustomer">+ Add customer</button></div><div class="card"><table><thead><tr><th>Name</th><th>Phone</th><th>Outstanding</th><th></th></tr></thead><tbody>${state.customers.length?state.customers.map(c=>`<tr><td>${esc(c.name)}</td><td>${esc(c.phone||'—')}</td><td>${money(customerBalance(c))}</td><td><button class="secondary pay" data-id="${c.id}">Record payment</button></td></tr>`).join(''):'<tr><td colspan="4">No customers yet.</td></tr>'}</tbody></table></div>`},
expenses(){return `<div class="page-head"><h1>Expenses</h1><button id="addExpense">+ Record expense</button></div><div class="card"><table><thead><tr><th>Date</th><th>Category</th><th>Description</th><th>Method</th><th>Amount</th></tr></thead><tbody>${state.expenses.length?state.expenses.map(e=>`<tr><td>${e.date}</td><td>${esc(e.category)}</td><td>${esc(e.description||'—')}</td><td>${esc(e.payment)}</td><td>${money(e.amount)}</td></tr>`).join(''):'<tr><td colspan="5">No expenses yet.</td></tr>'}</tbody></table></div>`},
reports(){const m=metrics();return `<div class="page-head"><h1>Reports</h1><button id="export">Export CSV</button></div><div class="grid"><div class="card metric"><small>Recorded sales</small><strong>${money(total(state.sales))}</strong></div><div class="card metric"><small>Recorded expenses</small><strong>${money(total(state.expenses))}</strong></div><div class="card metric"><small>Gross profit estimate</small><strong>${money(state.sales.reduce((n,s)=>n+s.total-s.cost,0))}</strong></div><div class="card metric"><small>Outstanding debt</small><strong>${money(m.debt)}</strong></div></div><div class="card"><h2>Report notes</h2><p>Profit estimates use the cost price recorded when each sale was made. This is a management view, not tax or legal advice.</p></div>`},
assistant(){return `<div class="page-head"><div><h1>Business assistant</h1><p>Answers use only records stored in this business. Interpretations are clearly labelled.</p></div></div><div class="card"><div class="chat" id="chat"><div class="bubble">Ask “What were my sales?”, “What did I spend?”, “Who owes me money?”, or “What products are running low?”</div></div><form id="chatForm" class="chat-form"><input id="question" aria-label="Ask your business assistant" placeholder="Ask about your business"><button>Ask</button></form></div>`,
feedback(){const connected=!!state.apiBusinessId;return `<div class="page-head"><div><p class="eyebrow">HELP SHAPE BIZAI</p><h1>Your feedback matters</h1></div></div><div class="card">${connected?`<div class="connection">Connected to your secure BizAI account.</div><h2>How would you rate your overall experience?</h2><p>Select a gold star. Your rating is saved to your business account.</p><div class="stars" id="stars" role="radiogroup" aria-label="Overall experience rating">${[1,2,3,4,5].map(n=>`<button type="button" class="star" data-rating="${n}" aria-label="${n} star${n>1?'s':''}" role="radio" aria-checked="false">★</button>`).join('')}</div><form id="feedbackForm"><label>Anything else you'd like us to know?<textarea name="comment" maxlength="2000" placeholder="A suggestion, problem, or feature request — optional"></textarea></label><label>How likely are you to recommend BizAI Africa? (0–10)<select name="nps"><option value="">Skip</option>${Array.from({length:11},(_,n)=>`<option value="${n}">${n}</option>`).join('')}</select></label><button>Send feedback</button><p id="feedbackStatus" aria-live="polite"></p></form>`:`<div class="connection error">Connect a secure BizAI account to submit feedback. Ratings are never stored only in this browser.</div><form id="connectForm"><h2>Connect your account</h2><p>For local development, use the default API address. This uses your secure API session.</p><label>API address<input name="apiBase" value="${esc(state.apiBase||API_DEFAULT)}" required></label><label>Email<input name="email" type="email" required></label><label>Password<input name="password" type="password" minlength="12" required></label><div class="actions"><button name="action" value="login">Log in</button><button class="secondary" name="action" value="register">Create account</button></div><p id="connectStatus" aria-live="polite"></p></form>`}</div>`}
};
const bind={home(){ $('#quickSale').onclick=()=>openSale();$('#askAI').onclick=()=>{view='assistant';render()}},sales(){ $('#addSale').onclick=openSale;document.querySelectorAll('.receipt').forEach(b=>b.onclick=()=>receipt(b.dataset.id));},inventory(){ $('#addProduct').onclick=openProduct;},customers(){ $('#addCustomer').onclick=openCustomer;document.querySelectorAll('.pay').forEach(b=>b.onclick=()=>openPayment(b.dataset.id));},expenses(){ $('#addExpense').onclick=openExpense;},reports(){ $('#export').onclick=exportCsv;},assistant(){ $('#chatForm').onsubmit=ask;},feedback(){bindFeedback();}};
function bindFeedback(){let rating=0;const stars=[...document.querySelectorAll('.star')];const paint=n=>stars.forEach(s=>{const on=Number(s.dataset.rating)<=n;s.classList.toggle('selected',on);s.setAttribute('aria-checked',String(on));});stars.forEach(s=>{s.onclick=()=>{rating=Number(s.dataset.rating);paint(rating)}});const form=$('#feedbackForm');if(form){form.onsubmit=async e=>{e.preventDefault();const f=new FormData(form),comment=f.get('comment').trim(),nps=f.get('nps');if(!rating&&!comment&&!nps){$('#feedbackStatus').textContent='Please select a star, provide a recommendation score, or leave a comment.';return;}const status=$('#feedbackStatus');status.textContent='Sending…';try{await api('/feedback',{method:'POST',body:JSON.stringify({kind:rating?'rating':nps?'nps':'comment',feature:'overall_experience',rating:rating||undefined,nps:nps===''?undefined:Number(nps),comment:comment||undefined})});status.textContent='Thank you — your feedback was saved securely.';form.reset();rating=0;paint(0);}catch(error){status.textContent=error.message;}};return;}const connect=$('#connectForm');if(connect)connect.onsubmit=async e=>{e.preventDefault();const f=new FormData(connect),status=$('#connectStatus'),action=e.submitter?.value||'login';state.apiBase=f.get('apiBase').replace(/\/$/,'');save();status.textContent='Connecting…';try{await api(`/auth/${action}`,{method:'POST',body:JSON.stringify({email:f.get('email'),password:f.get('password')})});const profile=await api('/me');let business=profile.businesses[0];if(!business){if(!state.business?.countryCode)throw new Error('Create your business profile and choose its country first.');business=await api('/businesses',{method:'POST',body:JSON.stringify({name:state.business.name,countryCode:state.business.countryCode,currencyCode:state.business.currency})});}state.apiBusinessId=business.id;save();render();}catch(error){status.textContent=error.message;}};}
function modal(html,submit){const d=$('#modal');d.innerHTML=html;d.showModal();d.querySelector('form').onsubmit=e=>{e.preventDefault();submit(new FormData(e.target));d.close();};d.querySelector('[data-cancel]')?.addEventListener('click',()=>d.close());}
const buttons='<div class="actions"><button>Confirm</button><button type="button" data-cancel class="secondary">Cancel</button></div>';
function openProduct(){modal(`<form><h2>Add product</h2><div class="form-grid"><label>Product name<input name="name" required></label><label>SKU<input name="sku"></label><label>Cost price<input name="cost" type="number" min="0" step=".01" required></label><label>Selling price<input name="sell" type="number" min="0" step=".01" required></label><label>Quantity<input name="qty" type="number" min="0" required></label><label>Minimum stock<input name="min" type="number" min="0" value="0" required></label></div>${buttons}</form>`,f=>{state.products.push({id:id(),name:f.get('name'),sku:f.get('sku'),cost:+f.get('cost'),sell:+f.get('sell'),qty:+f.get('qty'),min:+f.get('min')});save();render();});}
function openCustomer(){modal(`<form><h2>Add customer</h2><label>Name<input name="name" required></label><label>Phone<input name="phone" inputmode="tel"></label>${buttons}</form>`,f=>{state.customers.push({id:id(),name:f.get('name'),phone:f.get('phone')});save();render();});}
function openSale(){if(!state.products.length){alert('Add a product before recording a sale.');view='inventory';render();return;}modal(`<form><h2>Confirm sale</h2><p>Review this transaction before saving.</p><div class="form-grid"><label>Product<select name="product" required>${state.products.map(p=>`<option value="${p.id}">${esc(p.name)} (${p.qty} available)</option>`).join('')}</select></label><label>Quantity<input name="qty" type="number" value="1" min="1" required></label><label>Unit price<input name="price" type="number" min="0" step=".01" required></label><label>Discount<input name="discount" type="number" min="0" value="0" step=".01"></label><label>Customer<select name="customer"><option value="">Walk-in customer</option>${state.customers.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></label><label>Payment<select name="payment"><option>Cash</option><option>Mobile money</option><option>Bank transfer</option><option>Card</option><option>Credit</option></select></label><label>Date<input name="date" type="date" value="${today()}" required></label></div>${buttons}</form>`,f=>{const p=state.products.find(p=>p.id===f.get('product')),q=+f.get('qty');if(q>p.qty){alert(`Only ${p.qty} ${p.name} available.`);return;}const total=Math.max(0,q*(+f.get('price'))-(+f.get('discount')));state.sales.push({id:id(),productId:p.id,productName:p.name,qty:q,total,cost:q*p.cost,customerId:f.get('customer')||null,payment:f.get('payment'),date:f.get('date')});p.qty-=q;save();render();});}
function openExpense(){modal(`<form><h2>Record expense</h2><div class="form-grid"><label>Category<select name="category"><option>Rent</option><option>Utilities</option><option>Transport</option><option>Stock purchase</option><option>Marketing</option><option>Equipment</option><option>Other</option></select></label><label>Amount<input name="amount" type="number" min="0" step=".01" required></label><label>Payment method<select name="payment"><option>Cash</option><option>Mobile money</option><option>Bank transfer</option><option>Card</option></select></label><label>Date<input name="date" type="date" value="${today()}" required></label><label class="full">Description<input name="description"></label></div>${buttons}</form>`,f=>{state.expenses.push({id:id(),category:f.get('category'),amount:+f.get('amount'),payment:f.get('payment'),date:f.get('date'),description:f.get('description')});save();render();});}
function openPayment(customerId){const c=state.customers.find(c=>c.id===customerId);modal(`<form><h2>Record payment</h2><p>${esc(c.name)} currently owes <b>${money(customerBalance(c))}</b>.</p><label>Amount<input name="amount" type="number" min=".01" step=".01" required></label><label>Date<input name="date" type="date" value="${today()}" required></label>${buttons}</form>`,f=>{const amt=+f.get('amount');if(amt>customerBalance(c)){alert('Payment cannot exceed the outstanding balance.');return;}state.payments.push({id:id(),customerId,amount:amt,date:f.get('date')});save();render();});}
function ask(e){e.preventDefault();const q=$('#question').value.trim();if(!q)return;const chat=$('#chat');chat.insertAdjacentHTML('beforeend',`<div class="bubble me">${esc(q)}</div>`);chat.insertAdjacentHTML('beforeend',`<div class="bubble">${answer(q)}</div>`);$('#question').value='';chat.scrollTop=chat.scrollHeight;}
function answer(q){const x=q.toLowerCase(),m=metrics();if(!state.sales.length&&!state.expenses.length)return "I don't have enough recorded data to answer that yet.";if(/sales|sell|revenue/.test(x))return `<b>Calculated from records:</b> total recorded sales are ${money(total(state.sales))}; today is ${money(m.rev)}.`;if(/spend|expense/.test(x))return `<b>Calculated from records:</b> total recorded expenses are ${money(total(state.expenses))}; today is ${money(m.exp)}.`;if(/owe|debt|balance/.test(x)){const owing=state.customers.filter(c=>customerBalance(c)>0);return owing.length?`<b>Calculated from records:</b> ${owing.map(c=>`${esc(c.name)} (${money(customerBalance(c))})`).join(', ')}. Total: ${money(m.debt)}.`:'No customers currently have a recorded outstanding balance.';}if(/low|stock|reorder/.test(x)){const low=state.products.filter(p=>p.qty<=p.min);return low.length?`<b>Calculated from records:</b> ${low.map(p=>`${esc(p.name)} (${p.qty} remaining)`).join(', ')} need attention.`:'No products are currently at or below their minimum stock level.';}if(/profit|perform/.test(x))return `<b>Calculated from records:</b> today’s estimated profit is ${money(m.profit)} (sales minus recorded cost of goods and expenses). <i>Interpretation:</i> record more days to compare your weekly performance reliably.`;return "I can help with recorded sales, expenses, estimated profit, outstanding debt, and low stock. I don't have enough structured data to answer that question.";}
function exportCsv(){const rows=[['Type','Date','Description','Amount','Payment'],...state.sales.map(s=>['Sale',s.date,s.productName,s.total,s.payment]),...state.expenses.map(e=>['Expense',e.date,e.description||e.category,e.amount,e.payment])];download('bizai-report.csv',rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n'),'text/csv');}
function receipt(sid){const s=state.sales.find(x=>x.id===sid), c=state.customers.find(c=>c.id===s.customerId);download(`receipt-${s.id}.html`,`<!doctype html><title>Receipt</title><h1>${esc(state.business.name)}</h1><p>Receipt · ${s.date}</p><p>${esc(s.productName)} × ${s.qty}</p><h2>${money(s.total)}</h2><p>Payment: ${esc(s.payment)}<br>Customer: ${esc(c?.name||'Walk-in')}</p>`,'text/html');}
function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href);}
window.addEventListener('online',save);window.addEventListener('offline',save);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');save();render();
